### ISSUE TITLE
Possível erro com o emulador

### ISSUE THREAD

**Issue by ghost** [Rocketseat/ambiente-react-native#10]
Estive seguindo o passo-a-passo do curso de React Native (aliás, ótimo curso <3) e na hora do "react-native run-android" dá o seguinte erro:

`$ react-native run-android`
```sh
info Starting JS server...
info Building and installing the app on the device (cd android && gradlew.bat app:installDebug)...
Erro: Não foi possível localizar nem carregar a classe principal org.gradle.wrapper.GradleWrapperMain
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug
```

Este é o meu ambiente de desenvolvimento para o React Native de acordo com o comando "react-native info":

`$ react-native info`
```
info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
      Memory: 2.46 GB / 7.91 GB
    Binaries:
      Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842
```

**Comment by rafaelmegda** [comment]
Ola TraumereiPV você conseguiu solucionar este erro? No meu caso também estou com o mesmo problema.

**Comment by pellizzetti** [comment]
@TraumereiPV @rafaelmegda Qual versão do JDK estão usando? Se for a 11 façam downgrade para a 8.

**Comment by rafaelmegda** [comment]
Estou utilizando as versões abaixo:



Rafael Megda
(17) 98821-7169

“The Faith is all”

De: Guilherme Pellizzetti
Enviado:sexta-feira, 29 de março de 2019 11:09
Para: Rocketseat/ambiente-react-native
Cc:Rafael Megda; Mention
Assunto: Re: [Rocketseat/ambiente-react-native] Possível erro com o emulador (#10)

@TraumereiPV @rafaelmegda Qual versão do JDK estão usando? Se for a 11 façam downgrade para a 8.

**Comment by pellizzetti** [comment]
@rafaelmegda Ficou em branco o resto do seu comentário. 😅

**Comment by cssorlandi** [comment]
@rafaelmegda Conseguiu algum progresso com o problema?

Estamos no aguardo do seu retorno para evoluirmos sobre o assunto ;)

**Comment by rafaelmegda** [comment]
Eu estava iniciando o projeto sem ter instalado corretamente o Emulador.

De toda a forma, eu ainda estou com dificuldade para utilizar o Genymotion,
ele inicia mas só fica em "boot". Na pasta do SDK o comando sdb devices
informa que não conectou com o Genymotion!

Eu estou utilizando meu dispositivo celular, mas mesmo assim ainda não esta
atualizando o código com facilidade. Estou com um pouco de dificuldade para
configurar o ambiente, terminar a instalação para rodar a emulação do
código.

De toda forma, ainda vou pesquisar e aprofundar para tentar resolver isso.

Abraços

Rafael

Em seg, 1 de abr de 2019 às 15:04, Claudio Orlandi <notifications@github.com>
escreveu:

**Comment by icbertoncelo** [comment]
@rafaelmegda estou passando pelo mesmo problema. Meu genymmotion permanece com o state = booting mesmo com ele em execução. Aí quando eu dou o comando run-android acusa esse erro.

Não consigo encontrar a solução.

**Comment by icbertoncelo** [comment]
https://github.com/Rocketseat/ambiente-react-native/blob/master/erros-comuns.md

Só acessar o link pra corrigir o erro!!!

**Comment by pellizzetti** [comment]
@icbertoncelo Que bom que conseguiu resolver! :D

@rafaelmegda A título de informação, se possível, cola aqui o output do comando: `react-native info`? Como você está tendo problemas com o ambiente, ter informação do sistema nos ajuda a tentar melhorar o documento caso necessário. <3

**Comment by ghost** [comment]
@rafaelmegda Ainda não! Vou retornar a usar o windows 10 (Troquei para o Fedora para testar, mas não deu certo) e vou dar um downgrade no JDK para a versão 8 como o @pellizzetti pediu!

**Comment by pellizzetti** [comment]
Conseguiu resolver @TraumereiPV?

**Comment by icbertoncelo** [comment]
Aparentemente é necessário setar o ip todas as vezes que startar o emulador.

**Comment by apudo10** [comment]
Boa noite, caso não tenham resolvido, segue a solução!! pelo menos funcionou pra mim...abs

yarn add react-native-navigation@latest

**Comment by Lucas15andrade** [comment]
Esse [link](https://stackoverflow.com/questions/43521533/error-could-not-find-or-load-main-class-org-gradle-wrapper-gradlewrappermain) pode te ajudar.

Isso daqui funcionou para mim: 

I fixed this issue doing these two simple steps:

1) Delete Android and iOS folders

2) Execute the next line

react-native eject

3) Run!

react-native run-android

**Comment by ghost** [comment]
Resolvi o problema faz um tempo, peço desculpas pela demora

O problema foi que eu estava usando uma versão do JDK que não era a 8; eu estava no Windows e então tentei no Fedora 29 e no 30, foi aí que descobri sobre as versões do Java (Se eu não me engano, no primeiro guia não estava tão explicito que tinha que usar a versão 8)

Espero que alguém com o mesmo problema tenha conseguido resolver, e obrigado pelas respostas <3

**Comment by DyogoViana** [comment]
alguém conseguiu ?

o meu tá com tudo certo do qual foi comentado aqui, mas mesmo assim n tá rolando.

**Comment by tjdesigner** [comment]
> Resolvi o problema faz um tempo, peço desculpas pela demora
> 
> O problema foi que eu estava usando uma versão do JDK que não era a 8; eu estava no Windows e então tentei no Fedora 29 e no 30, foi aí que descobri sobre as versões do Java (Se eu não me engano, no primeiro guia não estava tão explicito que tinha que usar a versão 8)
> 
> Espero que alguém com o mesmo problema tenha conseguido resolver, e obrigado pelas respostas <3

Exatamente!
Eu tbm estava com duas versões instaladas, retirei a outra que não era a 8 e funcionou perfeitamente.
Valeu!!

**Comment by emersonjds** [comment]
Conforme falado nos comentarios anteriores é necessario ver qual a versao do Java instalado na maquina para o setup inicial.

Na propria documentação pede para que a versao utilizada seja a jdk8

https://reactnative.dev/docs/environment-setup

Espero ter ajudado

**Comment by jamesson-dev** [comment]
talvez este codigo possa funcionar, para voce!

`react-native start --reset-cache`

para mim funcionou
