### ISSUE TITLE
Tela do emulador não carrega

### ISSUE THREAD

**Issue by albertojcvs** [Rocketseat/ambiente-react-native#16]
Quando eu abro o  emulador do android no genymotion a tela fica toda preta, ou seja, não aparece nada
![Screenshot_2](https://user-images.githubusercontent.com/49288213/55586580-aff18100-56ff-11e9-9c38-f5de89f705a6.jpg)
só que quando eu uso o screenshot do próprio emulador a imagem que sai é o correto:
![screenshot-2019-04-04_15 17 33 436](https://user-images.githubusercontent.com/49288213/55589665-3198dd00-5707-11e9-8a00-fbbd3a36974c.png)

Então queria saber se alguém sabe como ajeitar esse problema

**Comment by pellizzetti** [comment]
Qual sistema operacional?

Você usa algum VPN ou Proxy? Se sim, desabilite e tente novamente.

**Comment by albertojcvs** [comment]
Uso o Windows 10 e não utilizo nenhuma VPN ou Proxy

**Comment by pellizzetti** [comment]
@albertojcvs

Na sua lista de `devices`:
1. Clique com o botão direito no seu `virtual device`.
2. Selecione **Generate log archive**.
    - Escolha onde seram salvos os arquivos gerados.
3. Espere até os arquivos serem gerados e feche a tela.

Desses arquivos gerados anexa aqui todos que contenham no nome do arquivo o nome do teu `virtual device` e o `general-genymotion.log`.

**Comment by albertojcvs** [comment]
Esse é todo o arquivo:
[genymotion-logs-20190405-130659.zip](https://github.com/Rocketseat/ambiente-react-native/files/3048752/genymotion-logs-20190405-130659.zip)

Esse é o do virtual device:
[Uploading Samsung Galaxy S8-VBox.log…](


[Samsung Galaxy S8-VBoxHardening.log](https://github.com/Rocketseat/ambiente-react-native/files/3048763/Samsung.Galaxy.S8-VBoxHardening.log)
[Samsung Galaxy S8-vmmachine.log](https://github.com/Rocketseat/ambiente-react-native/files/3048764/Samsung.Galaxy.S8-vmmachine.log)
[Samsung Galaxy S8-genymotion-player.log](https://github.com/Rocketseat/ambiente-react-native/files/3048765/Samsung.Galaxy.S8-genymotion-player.log)
[Samsung Galaxy S8-logcat.txt](https://github.com/Rocketseat/ambiente-react-native/files/3048766/Samsung.Galaxy.S8-logcat.txt)
[Samsung Galaxy S8-logcat-em7844.txt](https://github.com/Rocketseat/ambiente-react-native/files/3048767/Samsung.Galaxy.S8-logcat-em7844.txt)

)
Esses são o do genymotion:
[general-genymotion.log](https://github.com/Rocketseat/ambiente-react-native/files/3048793/general-genymotion.log)
[general-genymotionadbtunneld.log](https://github.com/Rocketseat/ambiente-react-native/files/3048794/general-genymotionadbtunneld.log)

**Comment by pellizzetti** [comment]
@albertojcvs Nos logs contém `Shader program is not linked`

Isso quer dizer que é alguma das seguintes situações:

- Genymotion não suporta sua placa de vídeo mais. Consulte https://www.genymotion.com/help/desktop/faq/#supported-graphics-cards.
- Se você estiver usando um notebook com duas placas de vídeo (e.g. Intel/Nvidia ou Intel/AMD, etc), verifique se está usando a mais recente/poderosa das duas.
- O driver da sua placa de vídeo está desatualizado. Atualize para a versão mais recente.

Se nada funcionar tenta o downgrade do Genymotion para 2.12.2. Você pode baixá-lo em: https://dl.genymotion.com/releases/genymotion-2.12.2/genymotion-2.12.2.exe

**Comment by pellizzetti** [comment]
@albertojcvs Conseguiu?

**Comment by albertojcvs** [comment]
Eu fui no site da genymotion, no meu caso era porque a minha placa de vídeo é inferior a mínima que eles pedem. Aí por enquanto estou o usando o expo. Mas depois vou tentar baixar o Android Studio

**Comment by pellizzetti** [comment]
Ok, vou fechar essa issue. Se tiver algum imprevisto/dúvida no uso do Android Studio pode abrir outra issue que te auxiliamos. :)
