### ISSUE TITLE
Utilizando outros emuladores

### ISSUE THREAD

**Issue by diego3g** [Rocketseat/ambiente-react-native#3]
Nox
ARC
Android AVD

**Comment by TauanMatos** [comment]
Como posso usar o emulador do android sdk ao invés do genymotion? Tem alguma config a mais pra ser feita?

**Comment by diego3g** [comment]
@TauanMatos Não, teoricamente é o mesmo processo.

**Comment by alangabrielbs** [comment]
Alguem pode me ajudar a configurar o nox? mero iniciante aqui...
