### ISSUE TITLE
Passo a passo para outras distribuições

### ISSUE THREAD

**Issue by robsonsilv4** [Rocketseat/ambiente-react-native#4]
Eu posso adicionar os passos de instalação necessários para o Arch Linux, com isso, o guia estaria abrangindo as distribuições mais populares atualmente segundo o [DistroWarch](https://distrowatch.com/dwres.php?resource=popularity).

**Comment by pellizzetti** [comment]
Fala Robson,

Adoraríamos receber uma PR com instruções para Arch sim! <3

**Comment by robsonsilv4** [comment]
Opa, já vou começar a escrever então.

Mas você prefere que adicione junto ao passo a passo para o Ubuntu, diferenciando cada ou que crie um novo markdown somente para o Arch Linux e adicione na página principal?

**Comment by pellizzetti** [comment]
Isso, acredito que poderia manter a estrutura de arquivos como está e criar uma divisão com uma parte passos pro Ubuntu (deb) e outra com os passos Arch.

**Comment by cssorlandi** [comment]
@robsonsilv4 Como já recebemos e fizemos o Merge da sua PR, estarei fechando essa Issue.

Caso tenha mais alguma sugestão pode reabri-lá ou até mesmo criar uma nova ;)
