### ISSUE TITLE
Problemas com o Yarn....

### ISSUE THREAD

**Issue by tonkunz** [Rocketseat/ambiente-react-native#7]
Estava tendo um problema ao executar o comando `react-native init hunt` (Seguindo os passos do curso de react-native da Rocketseat).
O feedback do erro terminava por avisar que:
Command `yarn add react-native --exact` failed.
Lembrei que tinha instalado o react-native usando o yarn:
`yarn global add react-native-cli`

Executei alguns passos da seguinte issue: [Unable to install react-native project using yarn #3227](https://github.com/yarnpkg/yarn/issues/3227)
Contudo, o que resolveu foi desinstalar o yarn mesmo.

Não sei se mais gente teve o mesmo problema  para ser inserido nos 'erros-comuns.md' do repo.

PS: este erro ocorreu no meu desktop (Windows 10 pro), no meu notebook (ubuntu 18.04) aparentemente tudo foi normal! :)

**Comment by cssorlandi** [comment]
@tonkunz Aparentemente você conseguiu resolver o problema, que por sinal é estranho de acontecer, como você mesmo presenciou, que com a mudança de sistemas funcionou corretamente.

Caso tenha mais algum problema ou dúvida, não hesite em reabrir a Issue ou criar uma nova.
